steps:
  # Paso para construir la imagen Docker del backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jenkinsgpc/jenkinsgpc-backend', './api']
  
  # Paso para empujar la imagen Docker del backend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-backend']

  # Paso para construir la imagen Docker del frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jenkinsgpc/jenkinsgpc-frontend', './site']

  # Paso para empujar la imagen Docker del frontend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-frontend']

# Especifica la ubicación del bucket de Cloud Storage para almacenar las imágenes
artifacts:
  objects:
    location: 'gs://proyecto-jenkins-gcp/'  # Ubicación para almacenar las imágenes Docker
    paths:
      - 'api/*'  # Ruta para los artefactos del backend
      - 'site/*'  # Ruta para los artefactos del frontend

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://proyecto-jenkins-gcp'
