steps:
  # Paso para construir y empujar la imagen Docker del backend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend'
      - './api'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-backend']

  # Paso para construir y empujar la imagen Docker del frontend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend'
      - './site'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-frontend']

  # Elimina el contenido del directorio output/suggested si existe
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -d "output/suggested" ]; then
          echo "Eliminando el contenido existente del directorio output/suggested..."
          rm -rf output/suggested/*
        fi

  # Pasos para desplegar la aplicación en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=./api/deployment-backend.yaml
      - --image=gcr.io/jenkinsgpc/jenkinsgpc-backend
      - --location=us-central1-c
      - --cluster=jenkins-cicd-cluster
      - --save-config=false  # Deshabilita la generación de archivos de configuración sugeridos

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=./site/deployment-frontend.yaml
      - --image=gcr.io/jenkinsgpc/jenkinsgpc-frontend
      - --location=us-central1-c
      - --cluster=jenkins-cicd-cluster
      - --save-config=false  # Deshabilita la generación de archivos de configuración sugeridos

# Especifica la ubicación del bucket de Cloud Storage para almacenar las imágenes y artefactos
artifacts:
  objects:
    location: 'gs://proyecto-jenkins-gcp/'  # Ubicación para almacenar las imágenes Docker y los artefactos
    paths:
      - 'api/*'  # Ruta para los artefactos del backend
      - 'site/*'  # Ruta para los artefactos del frontend

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://proyecto-jenkins-gcp'
