steps:
  # Paso para verificar si el directorio output/suggested está vacío
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if gsutil ls -r gs://proyecto-jenkins-gcp/output/suggested | grep -q .; then
          echo "El directorio output/suggested no está vacío."
        else
          echo "El directorio output/suggested está vacío. Puede continuar."
        fi

  # Pasos anteriores para construir y empujar las imágenes Docker

  # Paso para construir y empujar la imagen Docker del backend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - './api'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1']

  # Paso para construir y empujar la imagen Docker del frontend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - './site'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1']

  # Pasos para desplegar la aplicación en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=./api/deployment-backend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - '--location=us-central1-c'
      - '--cluster=jenkins-cicd-cluster'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=./site/deployment-frontend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - '--location=us-central1-c'
      - '--cluster=jenkins-cicd-cluster'

  # Paso adicional para copiar las imágenes Docker a Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'gs://jenkinsgpc_cloudbuild/*'
      - 'gs://proyecto-jenkins-gcp/artifacts/'

# Especifica la ubicación del bucket de Cloud Storage para almacenar las imágenes y artefactos
artifacts:
  objects:
    location: 'gs://proyecto-jenkins-gcp/'  
    paths:
      - 'api/*'  
      - 'site/*'  

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://proyecto-jenkins-gcp'
