steps:
  # Pasos anteriores para construir y empujar las imágenes Docker
  
  # Eliminar el contenido del directorio "expanded/suggested"
  - name: 'gcr.io/cloud-builders/gke-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        rm -rf expanded/suggested || true

  # Paso para construir y empujar la imagen Docker del frontend a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - './site'  # Utilizamos la ruta correcta del frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'

  # Pasos para desplegar el frontend en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'prepare'
      - '--filename=./site/deployment-frontend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - '--app=jenkinsgpc-frontend'
      - '--version=v1'
      - '--output=expanded'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./site/deployment-frontend.yaml'
      - '--cluster=jenkins-cicd-cluster'
      - '--location=us-central1-c'

  # Paso para construir y empujar la imagen Docker del backend a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - './api'
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'

  # Pasos para desplegar el backend en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'prepare'
      - '--filename=./api/deployment-backend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - '--app=jenkinsgpc-backend'
      - '--version=v1'
      - '--output=expanded'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./api/deployment-backend.yaml'
      - '--cluster=jenkins-cicd-cluster'
      - '--location=us-central1-c'

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://jenkinsgpc_cloudbuild'
