steps:
  # Paso para construir y empujar la imagen Docker del backend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend'
      - './api'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-backend']

  # Paso para construir y empujar la imagen Docker del frontend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend'
      - './site'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-frontend']

  # Crear un directorio temporal para los archivos de salida sugeridos
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creando directorio temporal para los archivos sugeridos..."
        mkdir -p temp_output_directory

  # Pasos para desplegar la aplicación en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=./api/deployment-backend.yaml
      - --image=gcr.io/jenkinsgpc/jenkinsgpc-backend
      - --location=us-central1-c
      - --cluster=jenkins-cicd-cluster
    # Redirigir la salida de los archivos sugeridos a un directorio temporal
    - '>'
    - 'temp_output_directory/output.log'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=./site/deployment-frontend.yaml
      - --image=gcr.io/jenkinsgpc/jenkinsgpc-frontend
      - --location=us-central1-c
      - --cluster=jenkins-cicd-cluster
    # Redirigir la salida de los archivos sugeridos a un directorio temporal
    - '>'
    - 'temp_output_directory/output.log'

# Eliminar el directorio temporal después de utilizar los archivos sugeridos
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Eliminando el directorio temporal de archivos sugeridos..."
        rm -rf temp_output_directory

# Especifica la ubicación del bucket de Cloud Storage para almacenar las imágenes y artefactos
artifacts:
  objects:
    location: 'gs://proyecto-jenkins-gcp/'  # Ubicación para almacenar las imágenes Docker y los artefactos
    paths:
      - 'api/*'  # Ruta para los artefactos del backend
      - 'site/*'  # Ruta para los artefactos del frontend

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://proyecto-jenkins-gcp'

