steps:
  # Pasos anteriores para construir y empujar las imágenes Docker

  # Paso para construir y empujar la imagen Docker del backend a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - './api'
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'

  # Paso para construir y empujar la imagen Docker del frontend a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - './site'  # Utilizamos la ruta correcta del frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'

  # Pasos para desplegar la aplicación en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'prepare'
      - '--filename=./api/deployment-backend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - '--app=jenkinsgpc-backend'
      - '--version=v1'
      - '--output=expanded'
      - '--namespace=my-backend-namespace'  # Reemplaza "my-backend-namespace" con el namespace deseado para el backend
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./api/deployment-backend.yaml'
      - '--namespace=my-backend-namespace'  # Reemplaza "my-backend-namespace" con el namespace deseado para el backend
      - '--cluster=jenkins-cicd-cluster'
      - '--location=us-central1-c'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'prepare'
      - '--filename=./site/deployment-frontend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - '--app=jenkinsgpc-frontend'
      - '--version=v1'
      - '--output=expanded'
      - '--namespace=my-frontend-namespace'  # Reemplaza "my-frontend-namespace" con el namespace deseado para el frontend
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '--filename=./site/deployment-frontend.yaml'
      - '--namespace=my-frontend-namespace'  # Reemplaza "my-frontend-namespace" con el namespace deseado para el frontend
      - '--cluster=jenkins-cicd-cluster'
      - '--location=us-central1-c'

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://jenkinsgpc_cloudbuild'
