steps:
  # Paso para empujar la imagen Docker del backend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-backend']

  # Paso para empujar la imagen Docker del frontend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jenkinsgpc/jenkinsgpc-frontend']

# Paso para desplegar la aplicación en Kubernetes utilizando gke-deploy
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - run
    - --filename=./api/deployment-backend.yaml,./site/deployment-frontend.yaml
    - --image=gcr.io/jenkinsgpc/jenkinsgpc-backend,gcr.io/jenkinsgpc/jenkinsgpc-frontend
    - --location=us-central1-c
    - --cluster=jenkins-cicd-cluster

# Especifica la ubicación del bucket de Cloud Storage para almacenar las imágenes
artifacts:
  objects:
    location: 'gs://proyecto-jenkins-gcp/'  # Ubicación para almacenar las imágenes Docker
    paths:
      - 'api/*'  # Ruta para los artefactos del backend
      - 'site/*'  # Ruta para los artefactos del frontend

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://proyecto-jenkins-gcp'
