steps:
  # Pasos anteriores para construir y empujar las imágenes Docker

  # Paso para construir y empujar la imagen Docker del backend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - './api'
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'

  # Paso para construir y empujar la imagen Docker del frontend a GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - './site'
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'

  # Paso adicional para copiar las imágenes Docker desde Artifact Registry a Cloud Storage
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts docker images list --location=us --repository=gcr.io/jenkinsgpc --project=jenkinsgpc --format="value(imageUri)" | \
        gsutil -m cp -r -I gs://proyecto-jenkins-gcp/artifacts/

  # Pasos para desplegar la aplicación en Kubernetes utilizando gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=./api/deployment-backend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-backend:v1'
      - '--location=us-central1-c'
      - '--cluster=jenkins-cicd-cluster'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=./site/deployment-frontend.yaml'
      - '--image=gcr.io/jenkinsgpc/jenkinsgpc-frontend:v1'
      - '--location=us-central1-c'
      - '--cluster=jenkins-cicd-cluster'

# Especifica la ubicación del bucket de Cloud Storage para almacenar las imágenes y artefactos
artifacts:
  objects:
    location: 'gs://proyecto-jenkins-gcp/'  
    paths:
      - 'api/*'  
      - 'site/*'  

# Especifica el nombre del bucket para los registros de la compilación
logsBucket: 'gs://proyecto-jenkins-gcp'
